# Generated by Django 4.0.2 on 2022-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='archivo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivo_cotidiano',
            field=models.FileField(blank=True, null=True, upload_to='archivos_cotidianos'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivo_mensual',
            field=models.FileField(blank=True, null=True, upload_to='archivos_mensuales'),
        ),
    ]
