# Generated by Django 4.0.2 on 2022-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
