# Generated by Django 4.0.2 on 2022-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='link',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
